version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:038540414823:task-definition/ecs-fargate:1"
        LoadBalancerInfo:
          ContainerName: "NodeFargateEcs"
          ContainerPort: 3000